name: attendance_qr_system
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.4.1
  fluttertoast: ^8.0.9
  qr_flutter: ^4.0.0
  convex_bottom_bar: ^3.0.0
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  bcrypt: ^1.1.3
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.2
  flutter_speed_dial: ^5.0.0+1
  font_awesome_flutter: ^10.1.0
  go_router: ^14.2.7
  mailer: ^5.0.0
  shared_preferences: ^2.0.6
  screenshot: ^3.0.0
  path_provider: ^2.0.11
  gallery_saver: ^2.3.2
  image_picker: ^1.1.2
  google_ml_kit: ^0.18.1
  sn_progress_dialog: ^1.1.4
  uuid: ^4.5.1
  cached_network_image: ^3.2.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "Assets/qr_logo_foreground.png"
  adaptive_icon_background: "Assets/qr_logo_foreground.png"
  adaptive_icon_foreground: "Assets/qr_logo_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - Assets/
    - Assets/logo.png

  fonts:
    - family: Roboto
      fonts:
        - asset: font/RobotoCondensed-Regular.ttf
          weight: 500
        - asset: font/RobotoCondensed-SemiBold.ttf
          weight: 600